// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code++. Version 5.2.97.0. www.xsd2code.com
//    {"TargetFramework":"Net20","NameSpace":"WindowsHelper","Properties":{},"ClassParams":{},"Miscellaneous":{}}
//  </auto-generated>
// ------------------------------------------------------------------------------
#pragma warning disable
namespace WindowsHelper
{
    using System;
    using System.Diagnostics;
    using System.Xml.Serialization;
    using System.Runtime.Serialization;
    using System.Collections;
    using System.Xml.Schema;
    using System.ComponentModel;
    using System.Xml;
    using System.Collections.Generic;


    [DebuggerStepThrough]
    public partial class window
    {
        #region Private fields
        private int _selectedposition;
        private List<position> _position;
        private int _selectedsize;
        private List<size> _size;
        private List<condition> _condition;
        private string _process;
        private windowMode _mode;
        #endregion

        public window()
        {
            _condition = new List<condition>();
            _size = new List<size>();
            _position = new List<position>();
        }

        public int selectedposition
        {
            get
            {
                return _selectedposition;
            }
            set
            {
                _selectedposition = value;
            }
        }

        public List<position> position
        {
            get
            {
                return _position;
            }
            set
            {
                _position = value;
            }
        }

        public int selectedsize
        {
            get
            {
                return _selectedsize;
            }
            set
            {
                _selectedsize = value;
            }
        }

        public List<size> size
        {
            get
            {
                return _size;
            }
            set
            {
                _size = value;
            }
        }

        public List<condition> condition
        {
            get
            {
                return _condition;
            }
            set
            {
                _condition = value;
            }
        }

        public string process
        {
            get
            {
                return _process;
            }
            set
            {
                _process = value;
            }
        }

        public windowMode mode
        {
            get
            {
                return _mode;
            }
            set
            {
                _mode = value;
            }
        }
    }

    [DebuggerStepThrough]
    public partial class position
    {
        #region Private fields
        private int _x;
        private int _y;
        #endregion

        public int X
        {
            get
            {
                return _x;
            }
            set
            {
                _x = value;
            }
        }

        public int Y
        {
            get
            {
                return _y;
            }
            set
            {
                _y = value;
            }
        }
    }

    [DebuggerStepThrough]
    public partial class title
    {
        #region Private fields
        private string _value;
        private bool _isempty;
        private titleMode _mode;
        #endregion

        public string value
        {
            get
            {
                return _value;
            }
            set
            {
                _value = value;
            }
        }

        public bool isempty
        {
            get
            {
                return _isempty;
            }
            set
            {
                _isempty = value;
            }
        }

        public titleMode mode
        {
            get
            {
                return _mode;
            }
            set
            {
                _mode = value;
            }
        }
    }

    public enum titleMode
    {
        equals,
        notequals,
    }

    [DebuggerStepThrough]
    public partial class condition
    {
        #region Private fields
        private List<title> _title;
        private conditionWidth _width;
        private conditionHeight _height;
        #endregion

        public condition()
        {
            _height = new conditionHeight();
            _width = new conditionWidth();
            _title = new List<title>();
        }

        public List<title> title
        {
            get
            {
                return _title;
            }
            set
            {
                _title = value;
            }
        }

        public conditionWidth width
        {
            get
            {
                return _width;
            }
            set
            {
                _width = value;
            }
        }

        public conditionHeight height
        {
            get
            {
                return _height;
            }
            set
            {
                _height = value;
            }
        }
    }

    [DebuggerStepThrough]
    public partial class conditionWidth
    {
        #region Private fields
        private int _value;
        private int _accuracy;
        #endregion

        public int value
        {
            get
            {
                return _value;
            }
            set
            {
                _value = value;
            }
        }

        public int accuracy
        {
            get
            {
                return _accuracy;
            }
            set
            {
                _accuracy = value;
            }
        }
    }

    [DebuggerStepThrough]
    public partial class conditionHeight
    {
        #region Private fields
        private int _value;
        private int _accuracy;
        #endregion

        public int value
        {
            get
            {
                return _value;
            }
            set
            {
                _value = value;
            }
        }

        public int accuracy
        {
            get
            {
                return _accuracy;
            }
            set
            {
                _accuracy = value;
            }
        }
    }

    [DebuggerStepThrough]
    public partial class size
    {
        #region Private fields
        private int _width;
        private int _height;
        #endregion

        public int width
        {
            get
            {
                return _width;
            }
            set
            {
                _width = value;
            }
        }

        public int height
        {
            get
            {
                return _height;
            }
            set
            {
                _height = value;
            }
        }
    }

    public enum windowMode
    {
        hold,
        close,
        remember,
        topmost,
        notopmost,
    }
}
#pragma warning restore
